# Generated by Django 5.1.3 on 2024-12-03 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15, verbose_name='Тип списка')),
            ],
            options={
                'verbose_name': 'Тип списка',
                'verbose_name_plural': 'Типы списков',
            },
        ),
        migrations.AlterField(
            model_name='userlist',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.listtypes'),
        ),
    ]
