# Generated by Django 5.1.3 on 2024-12-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_listtypes_alter_userlist_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListTypes',
            new_name='ListType',
        ),
    ]
