# Generated by Django 5.1.3 on 2024-12-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_listtypes_listtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtype',
            name='translation',
            field=models.CharField(default='default', max_length=20, verbose_name='Перевод'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listtype',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Тип списка'),
        ),
    ]
