# Generated by Django 5.1.3 on 2024-12-03 23:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_genres_alter_game_rating'),
        ('users', '0004_listtype_translation_alter_listtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='rate',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.listtype', verbose_name='Тип списка'),
        ),
    ]
