# Generated by Django 5.1.3 on 2024-12-06 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userlist_game_alter_userlist_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlist',
            name='rate',
            field=models.SmallIntegerField(blank=True, help_text='Оценка от 1 до 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
    ]
