# Generated by Django 5.1.3 on 2024-12-06 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_listtype_order_alter_userlist_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.listtype', verbose_name='Тип списка'),
        ),
    ]
