# Generated by Django 5.1.3 on 2024-12-07 04:03

import sorl.thumbnail.fields
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userlist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=255, null=True, upload_to=users.models.get_image_path),
        ),
    ]
