# Generated by Django 5.1.3 on 2024-12-03 21:36

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_comment_user_game_comments_delete_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=games.models.get_poster_path, verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='game',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео (ссылка)'),
        ),
    ]
